name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: messeb/valgrind

    steps:
      - uses: actions/checkout@v3
      - name: Compile program
        run: make
      - name: Compile tests
        run: make test
      - name: Run tests
        run: ./test.sh -v
      - name: Run valgrind for memory leaks
        run: valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./test
