name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: messeb/valgrind

    steps:
      - uses: actions/checkout@v3
      - name: Compile program
        run: make
      - name: Compile tests
        run: make test
      - name: Run test
        run: valgrind --leak-check=yes ./test
