name: Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: messeb/valgrind

    steps:
      - uses: actions/checkout@v3
      - name: Compile program
        run: make
      - name: Compile tests
        run: make test
      - name: Run tests of the main funtion
        run: ./test.sh -v --valgrind --only-main
      - name: Run unit tests
        run: ./test.sh -v --valgrind --only-unit
